version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx-hello
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html:ro
