name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect & deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e
          echo "Starting deployment..."
          
          # Verify Docker is running
          docker ps || sudo service docker start
          
          # Navigate to project directory
          cd /root/nginx-hello || { echo "Directory not found"; exit 1; }
          
          # Update code
          git fetch origin
          git reset --hard origin/main
          
          # Update containers
          docker-compose pull
          docker-compose up -d --remove-orphans
          
          echo "Deployment completed successfully"
