name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e
          echo "Deploying to $(hostname)"
          
          cd /root/nginx-hello || exit 1
          git pull origin main
          docker-compose pull
          docker-compose up -d --remove-orphans
          
          echo "Deployment complete"
