name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect & deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 16.170.167.115
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/nginx-hello
          git pull origin main
          docker-compose pull
          docker-compose up -d --remove-orphans
